### PR TITLE
Add Docker-based development environment

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

### CODE REVIEW

**Comment by fuegas** [comment]
Patrick, what do you think of a `bin/` folder which has the scripts for the docker commands? To make usage a little easier? Like `bin/docker-build` or `bin/docker-lint`. Then we do not have to look up the documentation each time we want to use it 😉. My `$PATH` already includes a local `bin` folder by default.

**Comment by fuegas** [comment]
Also, the build docker gives an error when I try to use it:
```
ferdi@Fuji ac_anime-2017 (runenv) $ docker run --rm -it -v $(pwd):/code:z anime2017 lint
+ composer install
PHP Fatal error:  Uncaught RuntimeException: File not found: '/usr/share/php/Symfony/Component/autoload.php' in /usr/share/php/Fedora/Autoloader/functions.php:58
```

**Comment by puiterwijk** [comment]
I've now made it use a bin/ folder with local scripts, thanks for that idea.
The composer issue was related to a Fedora Rawhide breakage a while ago (rawhide is unstable at times), so instead I've just switched to use Fedora 26, which should be more stable.

**Comment by puiterwijk** [comment]
I've added instructions on adding the entry to the hosts file, and modified the `serve` script to bind to the hosts' localhost:8080.

**Comment by puiterwijk** [comment]
Thanks!

**Pull request merged**
